tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
cask "adoptopenjdk8"
brew "ant"
brew "aws-iam-authenticator"
brew "awscli"
brew "bochs"
brew "rlwrap"
brew "clojure"
brew "coreutils"
brew "elasticsearch@2.4", restart_service: true
brew "git"
brew "git-lfs"
brew "ipfs"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "neovim"
brew "p7zip"
brew "pandoc"
brew "python@2"
brew "ruby"
brew "sbcl"
brew "terminal-notifier"
brew "watchman"
brew "wget"
cask "1password"
cask "beaker-browser"
cask "calibre"
cask "emacs"
cask "gitkraken"
cask "google-chrome"
cask "google-cloud-sdk"
cask "ipfs"
cask "iterm2"
cask "jetbrains-toolbox"
cask "libreoffice"
cask "middleclick"
cask "sketch"
cask "slack"
cask "sublime-text"
cask "tableau"
cask "tunnelblick"
cask "virtualbox"
cask "visual-studio-code"
cask "zoomus"
mas "Disk Speed Test", id: 425264550
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "WireGuard", id: 1451685025
